-- Base schema for AK-47 and AK-50.
-- Apply with `supabase db push` or in SQL editor.

create table if not exists public.watchlists (
  id bigint generated by default as identity primary key,
  user_id text not null,
  symbol text not null,
  inserted_at timestamptz not null default now(),
  unique(user_id, symbol)
);

create table if not exists public.sessions (
  token text primary key,
  user_id text not null,
  email text,
  created_at timestamptz not null default now()
);

-- Optional user prefs placeholder.
create table if not exists public.user_preferences (
  user_id text primary key,
  default_symbol text,
  timezone text,
  updated_at timestamptz not null default now()
);

-- Recommended RLS policies for multi-tenant use.
alter table public.watchlists enable row level security;
alter table public.sessions enable row level security;
alter table public.user_preferences enable row level security;

-- Service-role policy: backend-only service key can fully manage records.
do $$ begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='watchlists' and policyname='service role watchlists all'
  ) then
    create policy "service role watchlists all"
      on public.watchlists
      for all
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;
end $$;

do $$ begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='sessions' and policyname='service role sessions all'
  ) then
    create policy "service role sessions all"
      on public.sessions
      for all
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;
end $$;

do $$ begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='user_preferences' and policyname='service role user_prefs all'
  ) then
    create policy "service role user_prefs all"
      on public.user_preferences
      for all
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;
end $$;
